'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FlightChangeDetail
    
    '''<summary>
    '''radCodeBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCodeBlock As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''tryme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tryme As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''lvflightlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvflightlist As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''hidIsClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidIsClose As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''hidData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidData As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
