'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home2
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadStyleSheetManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadStyleSheetManager1 As Global.Telerik.Web.UI.RadStyleSheetManager
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''RadAjaxManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxManager1 As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''content control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents content As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''imglogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imglogo As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''lblCarrier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarrier As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rblOneWayRoundTrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOneWayRoundTrip As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ddllBrokerCompanies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddllBrokerCompanies As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddllBrokers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddllBrokers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RadComboBoxACInclude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadComboBoxACInclude As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''OriginAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnAddLeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnAddLeg As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress2 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date2 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress3 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date3 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress4 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date4 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg4 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress5 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date5 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg5 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress6 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date6 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg6 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg7 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress7 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress7 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date7 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg7 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg8 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress8 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress8 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date8 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo8 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg8 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg9 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress9 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress9 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date9 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo9 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg9 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlLeg10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLeg10 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''OriginAddress10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OriginAddress10 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''DestinationAddress10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DestinationAddress10 As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''ddlPassengers10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPassengers10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''depart_date10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents depart_date10 As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''departtime_combo10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents departtime_combo10 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bttnRemoveLeg10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bttnRemoveLeg10 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdQuote As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdStartOver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdStartOver As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
