'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace GeoCode
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IGeocodeService", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResponseBase)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(RequestBase))>  _
    Partial Public Class GeocodeService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GeocodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReverseGeocodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CoastalPortal.My.MySettings.Default.CoastalPortal_GeoCode_GeocodeService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GeocodeCompleted As GeocodeCompletedEventHandler
        
        '''<remarks/>
        Public Event ReverseGeocodeCompleted As ReverseGeocodeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "ode", RequestNamespace:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ResponseNamespace:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Geocode(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As GeocodeRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GeocodeResponse
            Dim results() As Object = Me.Invoke("Geocode", New Object() {request})
            Return CType(results(0),GeocodeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GeocodeAsync(ByVal request As GeocodeRequest)
            Me.GeocodeAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GeocodeAsync(ByVal request As GeocodeRequest, ByVal userState As Object)
            If (Me.GeocodeOperationCompleted Is Nothing) Then
                Me.GeocodeOperationCompleted = AddressOf Me.OnGeocodeOperationCompleted
            End If
            Me.InvokeAsync("Geocode", New Object() {request}, Me.GeocodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGeocodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GeocodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GeocodeCompleted(Me, New GeocodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocode", RequestNamespace:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ResponseNamespace:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReverseGeocode(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal request As ReverseGeocodeRequest) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> GeocodeResponse
            Dim results() As Object = Me.Invoke("ReverseGeocode", New Object() {request})
            Return CType(results(0),GeocodeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReverseGeocodeAsync(ByVal request As ReverseGeocodeRequest)
            Me.ReverseGeocodeAsync(request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReverseGeocodeAsync(ByVal request As ReverseGeocodeRequest, ByVal userState As Object)
            If (Me.ReverseGeocodeOperationCompleted Is Nothing) Then
                Me.ReverseGeocodeOperationCompleted = AddressOf Me.OnReverseGeocodeOperationCompleted
            End If
            Me.InvokeAsync("ReverseGeocode", New Object() {request}, Me.ReverseGeocodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnReverseGeocodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReverseGeocodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReverseGeocodeCompleted(Me, New ReverseGeocodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeRequest
        Inherits RequestBase
        
        Private addressField As Address
        
        Private optionsField As GeocodeOptions
        
        Private queryField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Options() As GeocodeOptions
            Get
                Return Me.optionsField
            End Get
            Set
                Me.optionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Query() As String
            Get
                Return Me.queryField
            End Get
            Set
                Me.queryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Address
        
        Private addressLineField As String
        
        Private adminDistrictField As String
        
        Private countryRegionField As String
        
        Private districtField As String
        
        Private formattedAddressField As String
        
        Private localityField As String
        
        Private postalCodeField As String
        
        Private postalTownField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AddressLine() As String
            Get
                Return Me.addressLineField
            End Get
            Set
                Me.addressLineField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AdminDistrict() As String
            Get
                Return Me.adminDistrictField
            End Get
            Set
                Me.adminDistrictField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CountryRegion() As String
            Get
                Return Me.countryRegionField
            End Get
            Set
                Me.countryRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property District() As String
            Get
                Return Me.districtField
            End Get
            Set
                Me.districtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FormattedAddress() As String
            Get
                Return Me.formattedAddressField
            End Get
            Set
                Me.formattedAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Locality() As String
            Get
                Return Me.localityField
            End Get
            Set
                Me.localityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PostalTown() As String
            Get
                Return Me.postalTownField
            End Get
            Set
                Me.postalTownField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class GeocodeResult
        
        Private addressField As Address
        
        Private bestViewField As Rectangle
        
        Private confidenceField As Confidence
        
        Private confidenceFieldSpecified As Boolean
        
        Private displayNameField As String
        
        Private entityTypeField As String
        
        Private locationsField() As GeocodeLocation
        
        Private matchCodesField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BestView() As Rectangle
            Get
                Return Me.bestViewField
            End Get
            Set
                Me.bestViewField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Confidence() As Confidence
            Get
                Return Me.confidenceField
            End Get
            Set
                Me.confidenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ConfidenceSpecified() As Boolean
            Get
                Return Me.confidenceFieldSpecified
            End Get
            Set
                Me.confidenceFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property EntityType() As String
            Get
                Return Me.entityTypeField
            End Get
            Set
                Me.entityTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Locations() As GeocodeLocation()
            Get
                Return Me.locationsField
            End Get
            Set
                Me.locationsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")>  _
        Public Property MatchCodes() As String()
            Get
                Return Me.matchCodesField
            End Get
            Set
                Me.matchCodesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Rectangle
        Inherits ShapeBase
        
        Private northeastField As Location
        
        Private southwestField As Location
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Northeast() As Location
            Get
                Return Me.northeastField
            End Get
            Set
                Me.northeastField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Southwest() As Location
            Get
                Return Me.southwestField
            End Get
            Set
                Me.southwestField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GeocodeLocation)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(UserLocation)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Location
        
        Private altitudeField As Double
        
        Private altitudeFieldSpecified As Boolean
        
        Private latitudeField As Double
        
        Private latitudeFieldSpecified As Boolean
        
        Private longitudeField As Double
        
        Private longitudeFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Altitude() As Double
            Get
                Return Me.altitudeField
            End Get
            Set
                Me.altitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AltitudeSpecified() As Boolean
            Get
                Return Me.altitudeFieldSpecified
            End Get
            Set
                Me.altitudeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Latitude() As Double
            Get
                Return Me.latitudeField
            End Get
            Set
                Me.latitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LatitudeSpecified() As Boolean
            Get
                Return Me.latitudeFieldSpecified
            End Get
            Set
                Me.latitudeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Longitude() As Double
            Get
                Return Me.longitudeField
            End Get
            Set
                Me.longitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LongitudeSpecified() As Boolean
            Get
                Return Me.longitudeFieldSpecified
            End Get
            Set
                Me.longitudeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class GeocodeLocation
        Inherits Location
        
        Private calculationMethodField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CalculationMethod() As String
            Get
                Return Me.calculationMethodField
            End Get
            Set
                Me.calculationMethodField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class UserLocation
        Inherits Location
        
        Private confidenceField As Confidence
        
        Private confidenceFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Confidence() As Confidence
            Get
                Return Me.confidenceField
            End Get
            Set
                Me.confidenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ConfidenceSpecified() As Boolean
            Get
                Return Me.confidenceFieldSpecified
            End Get
            Set
                Me.confidenceFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum Confidence
        
        '''<remarks/>
        High
        
        '''<remarks/>
        Medium
        
        '''<remarks/>
        Low
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Polygon)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Circle)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Rectangle)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ShapeBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Polygon
        Inherits ShapeBase
        
        Private verticesField() As Location
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Vertices() As Location()
            Get
                Return Me.verticesField
            End Get
            Set
                Me.verticesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Circle
        Inherits ShapeBase
        
        Private centerField As Location
        
        Private distanceUnitField As DistanceUnit
        
        Private distanceUnitFieldSpecified As Boolean
        
        Private radiusField As Double
        
        Private radiusFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Center() As Location
            Get
                Return Me.centerField
            End Get
            Set
                Me.centerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceUnit() As DistanceUnit
            Get
                Return Me.distanceUnitField
            End Get
            Set
                Me.distanceUnitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DistanceUnitSpecified() As Boolean
            Get
                Return Me.distanceUnitFieldSpecified
            End Get
            Set
                Me.distanceUnitFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Radius() As Double
            Get
                Return Me.radiusField
            End Get
            Set
                Me.radiusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RadiusSpecified() As Boolean
            Get
                Return Me.radiusFieldSpecified
            End Get
            Set
                Me.radiusFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DistanceUnit
        
        '''<remarks/>
        Kilometer
        
        '''<remarks/>
        Mile
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ResponseSummary
        
        Private authenticationResultCodeField As AuthenticationResultCode
        
        Private authenticationResultCodeFieldSpecified As Boolean
        
        Private copyrightField As String
        
        Private faultReasonField As String
        
        Private statusCodeField As ResponseStatusCode
        
        Private statusCodeFieldSpecified As Boolean
        
        Private traceIdField As String
        
        '''<remarks/>
        Public Property AuthenticationResultCode() As AuthenticationResultCode
            Get
                Return Me.authenticationResultCodeField
            End Get
            Set
                Me.authenticationResultCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AuthenticationResultCodeSpecified() As Boolean
            Get
                Return Me.authenticationResultCodeFieldSpecified
            End Get
            Set
                Me.authenticationResultCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Copyright() As String
            Get
                Return Me.copyrightField
            End Get
            Set
                Me.copyrightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FaultReason() As String
            Get
                Return Me.faultReasonField
            End Get
            Set
                Me.faultReasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusCode() As ResponseStatusCode
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusCodeSpecified() As Boolean
            Get
                Return Me.statusCodeFieldSpecified
            End Get
            Set
                Me.statusCodeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TraceId() As String
            Get
                Return Me.traceIdField
            End Get
            Set
                Me.traceIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum AuthenticationResultCode
        
        '''<remarks/>
        None
        
        '''<remarks/>
        NoCredentials
        
        '''<remarks/>
        ValidCredentials
        
        '''<remarks/>
        InvalidCredentials
        
        '''<remarks/>
        CredentialsExpired
        
        '''<remarks/>
        NotAuthorized
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum ResponseStatusCode
        
        '''<remarks/>
        Success
        
        '''<remarks/>
        BadRequest
        
        '''<remarks/>
        ServerError
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GeocodeResponse)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ResponseBase
        
        Private brandLogoUriField As String
        
        Private responseSummaryField As ResponseSummary
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="anyURI", IsNullable:=true)>  _
        Public Property BrandLogoUri() As String
            Get
                Return Me.brandLogoUriField
            End Get
            Set
                Me.brandLogoUriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ResponseSummary() As ResponseSummary
            Get
                Return Me.responseSummaryField
            End Get
            Set
                Me.responseSummaryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeResponse
        Inherits ResponseBase
        
        Private resultsField() As GeocodeResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Public Property Results() As GeocodeResult()
            Get
                Return Me.resultsField
            End Get
            Set
                Me.resultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ConfidenceFilter)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class FilterBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class ConfidenceFilter
        Inherits FilterBase
        
        Private minimumConfidenceField As Confidence
        
        Private minimumConfidenceFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property MinimumConfidence() As Confidence
            Get
                Return Me.minimumConfidenceField
            End Get
            Set
                Me.minimumConfidenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MinimumConfidenceSpecified() As Boolean
            Get
                Return Me.minimumConfidenceFieldSpecified
            End Get
            Set
                Me.minimumConfidenceFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class GeocodeOptions
        
        Private countField As System.Nullable(Of Integer)
        
        Private countFieldSpecified As Boolean
        
        Private filtersField() As FilterBase
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Count() As System.Nullable(Of Integer)
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CountSpecified() As Boolean
            Get
                Return Me.countFieldSpecified
            End Get
            Set
                Me.countFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true)>  _
        Public Property Filters() As FilterBase()
            Get
                Return Me.filtersField
            End Get
            Set
                Me.filtersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class SizeOfint
        
        Private heightField As Integer
        
        Private heightFieldSpecified As Boolean
        
        Private widthField As Integer
        
        Private widthFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Height() As Integer
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeightSpecified() As Boolean
            Get
                Return Me.heightFieldSpecified
            End Get
            Set
                Me.heightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As Integer
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WidthSpecified() As Boolean
            Get
                Return Me.widthFieldSpecified
            End Get
            Set
                Me.widthFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Heading
        
        Private orientationField As Double
        
        Private orientationFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Orientation() As Double
            Get
                Return Me.orientationField
            End Get
            Set
                Me.orientationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property OrientationSpecified() As Boolean
            Get
                Return Me.orientationFieldSpecified
            End Get
            Set
                Me.orientationFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class UserProfile
        
        Private currentHeadingField As Heading
        
        Private currentLocationField As UserLocation
        
        Private deviceTypeField As DeviceType
        
        Private deviceTypeFieldSpecified As Boolean
        
        Private distanceUnitField As DistanceUnit
        
        Private distanceUnitFieldSpecified As Boolean
        
        Private iPAddressField As String
        
        Private mapViewField As ShapeBase
        
        Private screenSizeField As SizeOfint
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CurrentHeading() As Heading
            Get
                Return Me.currentHeadingField
            End Get
            Set
                Me.currentHeadingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CurrentLocation() As UserLocation
            Get
                Return Me.currentLocationField
            End Get
            Set
                Me.currentLocationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeviceType() As DeviceType
            Get
                Return Me.deviceTypeField
            End Get
            Set
                Me.deviceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DeviceTypeSpecified() As Boolean
            Get
                Return Me.deviceTypeFieldSpecified
            End Get
            Set
                Me.deviceTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceUnit() As DistanceUnit
            Get
                Return Me.distanceUnitField
            End Get
            Set
                Me.distanceUnitField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DistanceUnitSpecified() As Boolean
            Get
                Return Me.distanceUnitFieldSpecified
            End Get
            Set
                Me.distanceUnitFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IPAddress() As String
            Get
                Return Me.iPAddressField
            End Get
            Set
                Me.iPAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MapView() As ShapeBase
            Get
                Return Me.mapViewField
            End Get
            Set
                Me.mapViewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ScreenSize() As SizeOfint
            Get
                Return Me.screenSizeField
            End Get
            Set
                Me.screenSizeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DeviceType
        
        '''<remarks/>
        Desktop
        
        '''<remarks/>
        Mobile
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class ExecutionOptions
        
        Private suppressFaultsField As Boolean
        
        Private suppressFaultsFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property SuppressFaults() As Boolean
            Get
                Return Me.suppressFaultsField
            End Get
            Set
                Me.suppressFaultsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SuppressFaultsSpecified() As Boolean
            Get
                Return Me.suppressFaultsFieldSpecified
            End Get
            Set
                Me.suppressFaultsFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class Credentials
        
        Private applicationIdField As String
        
        Private tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ApplicationId() As String
            Get
                Return Me.applicationIdField
            End Get
            Set
                Me.applicationIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ReverseGeocodeRequest)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GeocodeRequest)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Partial Public Class RequestBase
        
        Private credentialsField As Credentials
        
        Private cultureField As String
        
        Private executionOptionsField As ExecutionOptions
        
        Private userProfileField As UserProfile
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Credentials() As Credentials
            Get
                Return Me.credentialsField
            End Get
            Set
                Me.credentialsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Culture() As String
            Get
                Return Me.cultureField
            End Get
            Set
                Me.cultureField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ExecutionOptions() As ExecutionOptions
            Get
                Return Me.executionOptionsField
            End Get
            Set
                Me.executionOptionsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property UserProfile() As UserProfile
            Get
                Return Me.userProfileField
            End Get
            Set
                Me.userProfileField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode")>  _
    Partial Public Class ReverseGeocodeRequest
        Inherits RequestBase
        
        Private locationField As Location
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Location() As Location
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")>  _
    Public Delegate Sub GeocodeCompletedEventHandler(ByVal sender As Object, ByVal e As GeocodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GeocodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GeocodeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeocodeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")>  _
    Public Delegate Sub ReverseGeocodeCompletedEventHandler(ByVal sender As Object, ByVal e As ReverseGeocodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReverseGeocodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GeocodeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeocodeResponse)
            End Get
        End Property
    End Class
End Namespace
