'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModelDetailPanel
    
    '''<summary>
    '''radCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
    
    '''<summary>
    '''TopStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TopStats As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblmodelid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmodelid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblrevenueexpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrevenueexpense As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblnonrevenueexpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnonrevenueexpense As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAverageEmtpyNM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAverageEmtpyNM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltotalrevenueexpense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltotalrevenueexpense As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblrevenuelegs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrevenuelegs As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblnonrevenuelegs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnonrevenuelegs As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblShortestEmtpyLeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShortestEmtpyLeg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLineBreaks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLineBreaks As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblrevenuemiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrevenuemiles As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblnonrevenuemiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnonrevenuemiles As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblLongestEmptyLeg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLongestEmptyLeg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblefficiency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblefficiency As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownNNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownNNumbers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownTripNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownTripNumbers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownOriginAirports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownOriginAirports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownDestAirports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownDestAirports As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DropDownFleetType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownFleetType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RBcalendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBcalendar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''chkLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLocal As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LinkPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkPending As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''chkGMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGMT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''LinkGMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkGMT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cmdRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefresh As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''radbtnAcceptAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radbtnAcceptAll As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''cmdSlideReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSlideReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdRecovery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRecovery As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdRemoveDH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveDH As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdScrubDH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdScrubDH As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modelstatusguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelstatusguage As Global.Telerik.Web.UI.RadLinearGauge
    
    '''<summary>
    '''hddnSearchMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnSearchMembers As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lvflightlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvflightlist As Global.System.Web.UI.WebControls.ListView
End Class
