'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OptimizerCalendar

    '''<summary>
    '''lblModelRunID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelRunID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rcbModelRun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rcbModelRun As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''lblDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDev As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblModelDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModelDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlPrintFOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrintFOS As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''FOSFlights1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FOSFlights1 As Global.CoastalPortal.FOSFlightsCalendar
End Class
